# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# os
os:
  - linux
# Set the python version to 2.7
python:
  - "2.7"
  - "3.6"
  - "3.7"

# Install the codecov pip dependency
install:
  - pip install sentencepiece
  - pip install gensim
  - pip install nltk
  - pip install fasttext

# Run the unit test
script:
  - python test.py
  # - coverage run tests.py
